version: "3.9"  # optional since v1.27.0

services:
  movie-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      LOCAL : "true"
      PORT : "8080"
      REDIS_URL : redis
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/app/pkg/mod
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=busha
    ports:
      - "5555:5432"
    volumes:
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh



  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test123!"
    ports:
      - "16543:80"
    depends_on:
      - db

  redis:
    container_name: "redis"
    image: redis:alpine
    ports:
      - "6379:6379"
